### PR TITLE
fix the issue of not accrue interest

### LINKED ISSUE #201: tokio-runtime-worker runtime::timestamp: `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0
image

### PR DESCRIPTION
**Pull request by yz89**
closes #201

### CODE REVIEW

File: pallets/loans/src/mock.rs [hunk 1]
```diff
@@ -281,14 +281,21 @@ pub(crate) fn run_to_block(n: BlockNumber) {
     Loans::on_finalize(System::block_number());
     for b in (System::block_number() + 1)..=n {
         System::set_block_number(b);
-        Timestamps::set_timestamp(6000 * b);
         Loans::on_initialize(System::block_number());
```
Comment (GopherJ) [inline pallets/loans/src/mock.rs:284]: looks like we don't have `on_initialize` anymore right?

Comment (yz89) [reply pallets/loans/src/mock.rs:284]: Yes. I leave the function here to maintain a test framework.

**Review by GopherJ — APPROVED** [review]

**Review by ayushmishra2005 — APPROVED** [review]
