### PR TITLE
Fix oracle price benchmarking issue 

### LINKED ISSUE #81: OraclePrice not ready while running benchmark
image

### PR DESCRIPTION
**Pull request by ayushmishra2005**
resolve #81

### CODE REVIEW

File: pallets/loans/src/mock.rs [hunk 1]
```diff
@@ -44,6 +46,7 @@ construct_runtime!(
         Tokens: orml_tokens::{Pallet, Storage, Event<T>, Config<T>},
         Balances: pallet_balances::{Pallet, Call, Storage, Event<T>},
         Currencies: orml_currencies::{Pallet, Call, Event<T>},
+        PricesPallet: pallet_prices::{Pallet, Storage, Call, Event<T>},
```
Comment (GopherJ) [inline pallets/loans/src/mock.rs:49]: Shall we rename `PricesPallet` to `Prices`?

**Comment by GopherJ** [comment]
@ayushmishra2005 on my side the numbers look different.

image

**Review by GopherJ — APPROVED** [review]

File: pallets/loans/src/lib.rs [hunk 2]
```diff
@@ -63,7 +65,7 @@ pub mod module {
     use super::*;
 
     #[pallet::config]
-    pub trait Config: frame_system::Config {
+    pub trait Config: frame_system::Config + pallet_prices::Config {
```
Comment (yz89) [inline pallets/loans/src/lib.rs:68]: Could you talk more about this?

Comment (ayushmishra2005) [reply pallets/loans/src/lib.rs:68]: @yz89 

We were getting `OracleCurrencyPriceNotReady ` because of https://github.com/parallel-finance/parallel/blob/defect/fix-oracle-price-benchmarking/pallets/loans/src/loan.rs#L134-L135

To fix that, I had to add `EmergencyPrice`,  https://github.com/parallel-finance/parallel/blob/defect/fix-oracle-price-benchmarking/pallets/loans/src/benchmarking.rs#L38

Thats why I added `pallet_prices`

File: pallets/loans/src/mock.rs [hunk 3]
```diff
@@ -135,6 +138,33 @@ impl pallet_balances::Config for Runtime {
...
+impl SortedMembers<AccountId> for OneToFive {
+    fn sorted_members() -> Vec<AccountId> {
+        vec![1, 2, 3, 4, 5]
+    }
+}
+
+impl pallet_prices::Config for Runtime {
+    type Event = Event;
+    type Source = MockDataProvider;
+    type FeederOrigin = EnsureSignedBy<OneToFive, AccountId>;
```
Comment (kaichaosun) [inline pallets/loans/src/mock.rs:165]: This is overkill, how about only signed by 1 account?
https://github.com/paritytech/substrate/blob/master/frame/node-authorization/src/mock.rs#L76

File: pallets/loans/src/mock.rs [hunk 4]
```diff
@@ -135,6 +138,33 @@ impl pallet_balances::Config for Runtime {
     type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;
 }
 
+pub type TimeStampedPrice = orml_oracle::TimestampedValue<OraclePrice, Moment>;
```
Comment (kaichaosun) [inline pallets/loans/src/mock.rs:141]: lower case `s`.

File: pallets/loans/src/lib.rs (hunk 2 above)
Comment (kaichaosun) [reply pallets/loans/src/lib.rs:68]: Emergency price is a different logic, probably not in good shape.
We better not use trait inheritance, it makes code hard to test and less structural. 
The error `OracleCurrencyPriceNotReady` should be resolved if you have a mock PriceFeeder.

File: pallets/loans/Cargo.toml [hunk 5]
```diff
@@ -26,6 +27,7 @@ sp-std             = { git = 'https://github.com/paritytech/substrate.git', bran
 lazy_static = { version = "1.4.0" }
 sp-core     = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1', version = '3.0.0', default-features = false }
 sp-io       = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1', version = '3.0.0', default-features = false }
+orml-oracle = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false}
```
Comment (kaichaosun) [inline pallets/loans/Cargo.toml:30]: This should be encapsulated in prices pallet.

File: pallets/loans/src/lib.rs (hunk 2 above)
Comment (ayushmishra2005) [reply pallets/loans/src/lib.rs:68]: I just checked. Even if we import orml_oracle, lot of changes are required in loan pallet. I am trying to find a soltion.

**Comment by GopherJ** [comment]
BTW, we deploy testnet by github actions, I'm not sure if it's a good idea to use https://github.com/sgeisler/cargo-remote to  generate weight numbers using our testnet instance and pull them back & push weights

**Comment by kaichaosun** [comment]
@GopherJ Substrate codebase has a CI task to do this.

**Comment by yz89** [comment]
Great work!

**Review by kaichaosun — APPROVED** [review]
👍
