### PR TITLE
Fix loans benchmarks

### LINKED ISSUE #267: Fix benchmarks
benchmarks are broken recently due to:

- loans benchmarks only use DOT but in vanilla we use KSM, which fails on `enable_currency` check
- liquidate_borrow has changed
- liquid-staking's reserve factor? not sure

### PR DESCRIPTION
**Pull request by ayushmishra2005**
resolved #267

### CODE REVIEW

**Review by GopherJ — APPROVED** [review]

**Comment by GopherJ** [comment]
cool!, I'm testing

File: pallets/loans/benchmarking/src/lib.rs [hunk 1]
```diff
@@ -222,34 +239,36 @@ benchmarks! {
...
         assert_ok!(ORMLOracle::<T, _>::feed_values(SystemOrigin::Root.into(),
             vec![(currency_id, price)]));
-        assert_ok!(Loans::<T>::mint(SystemOrigin::Signed(borrower.clone()).into(), DOT, INITIAL_AMOUNT));
-        assert_ok!(Loans::<T>::collateral_asset(SystemOrigin::Signed(borrower.clone()).into(), DOT, true));
-        assert_ok!(Loans::<T>::borrow(SystemOrigin::Signed(borrower.clone()).into(), DOT, borrowed_amount));
-        let total_borrows = pallet_loans::TotalBorrows::<T>::get(DOT);
+        <T as LoansConfig>::Currency::deposit(DOT, &alice.clone(), 100_000_000_0).unwrap();
+        <T as LoansConfig>::Currency::deposit(KSM, &alice.clone(), 100_000_000_0).unwrap();
+        <T as LoansConfig>::Currency::deposit(DOT, &bob.clone(), 100_000_000_0).unwrap();
+        <T as LoansConfig>::Currency::deposit(KSM, &bob.clone(), 100_000_000_0).unwrap();
```
Comment (yz89) [inline pallets/loans/benchmarking/src/lib.rs:252]: I think we can use `transfer_initial_balance` for Alice and Bob here.

**Comment by GopherJ** [comment]
looks like I'm still having an issue:


image

File: pallets/loans/benchmarking/src/lib.rs [hunk 2]
```diff
@@ -222,34 +239,36 @@ benchmarks! {
...
+        assert_ok!(Loans::<T>::mint(SystemOrigin::Signed(bob.clone()).into(), KSM, 200_000_000));
+        assert_ok!(Loans::<T>::mint(SystemOrigin::Signed(alice.clone()).into(), DOT, 200_000_000));
+        assert_ok!(Loans::<T>::collateral_asset(SystemOrigin::Signed(alice.clone()).into(), DOT, true));
+        assert_ok!(Loans::<T>::borrow(SystemOrigin::Signed(alice.clone()).into(), KSM, 100_000_000));
     }: {
-         let _ = Loans::<T>::liquidate_borrow(SystemOrigin::Signed(caller.clone()).into(), borrower, DOT, repay_amount, DOT);
+         let _ = Loans::<T>::liquidate_borrow(SystemOrigin::Signed(bob).into(), alice.clone(), KSM, 50_000_000, DOT);
```
Comment (yz89) [inline pallets/loans/benchmarking/src/lib.rs:258]: I don't think the `liquidate_borrow` can process successfully because Alice's shortfall is zero. You can let Alice have a positive shortfall by changing the price. https://github.com/parallel-finance/parallel/blob/master/pallets/loans/src/tests/liquidate_borrow.rs#L79

**Review by GopherJ — CHANGES_REQUESTED** [review]
looks like I'm still having an issue:


image

File: pallets/loans/benchmarking/src/lib.rs [hunk 3]
```diff
@@ -222,34 +239,36 @@ benchmarks! {
...
     }
     verify {
```
Comment (yz89) [inline pallets/loans/benchmarking/src/lib.rs:260]: Please make sure Bob has gotten the incentive token as well. https://github.com/parallel-finance/parallel/blob/master/pallets/loans/src/tests/liquidate_borrow.rs#L118

**Comment by ayushmishra2005** [comment]
> looks like I'm still having an issue:
> 
> image

@GopherJ Test-cases are running fine on my local. Where are you getting this error?

**Comment by GopherJ** [comment]
> > looks like I'm still having an issue:
> > image
> 
> @GopherJ Test-cases are running fine on my local. Where are you getting this error?

let me test again on a Linux

**Comment by ayushmishra2005** [comment]
> > > looks like I'm still having an issue:
> > > image
> > 
> > 
> > @GopherJ Test-cases are running fine on my local. Where are you getting this error?
> 
> let me test again on a Linux

@GopherJ Please hold your testing.

File: pallets/loans/benchmarking/src/lib.rs [hunk 4]
```diff
@@ -222,34 +261,39 @@ benchmarks! {
...
+         let _ = Loans::<T>::liquidate_borrow(SystemOrigin::Signed(bob.clone()).into(), alice.clone(), KSM, 50_000_000_00, DOT);
     }
     verify {
         assert_eq!(
-            pallet_loans::TotalBorrows::<T>::get(DOT),
-            total_borrows - repay_amount,
+            <T as LoansConfig>::Currency::free_balance(DOT, &alice),
+            800_000_000_00,
+        );
+        assert_eq!(
```
Comment (yz89) [inline pallets/loans/benchmarking/src/lib.rs:286]: liquidate_borrow has no effects on the free_balance of both Alive and Bob. I think it should check the borrow balance of Alice and the voucher_balance of Bob.

Comment (yz89) [reply pallets/loans/benchmarking/src/lib.rs:286]: Check Alice's borrow balance sample: https://github.com/parallel-finance/parallel/blob/master/pallets/loans/src/tests/liquidate_borrow.rs#L111

Comment (yz89) [reply pallets/loans/benchmarking/src/lib.rs:286]: The sample of checking Bob's voucher balance: https://github.com/parallel-finance/parallel/blob/master/pallets/loans/src/tests/liquidate_borrow.rs#L119

Comment (yz89) [reply pallets/loans/benchmarking/src/lib.rs:286]: Alice will reduce 50_000_000_00 borrow balance in this case and Bob will add 110_000_000_00 / Loans::exchange_rate(DOT) into voucher_balance.

**Review by yz89 — APPROVED** [review]

**Review by GopherJ — APPROVED** [review]
