### PR TITLE
fix the inconsistent liquidity calculation

### LINKED ISSUE #838: redeem_all failed after exchange_rate greater than initial value
Alice redeem_all failed even she had already repaid all the borrows.

```
2021-10-31 14:53:24.440 TRACE tokio-runtime-worker loans::redeem_allowed: [Parachain] asset_id: 100, redeemer: , voucher_amount: 149999992237450
2021-10-31 14:53:24.440 TRACE tokio-runtime-worker loans::get_price: [Parachain] price: 358309649709999980544000000
2021-10-31 14:53:24.440 TRACE tokio-runtime-worker loans::redeem_allowed: [Parachain] redeem_amount: 3000001086759, redeem_dffects_value: 537464669263297430236
2021-10-31 14:53:24.441 TRACE tokio-runtime-worker loans::get_price: [Parachain] price: 358309649709999980544000000
2021-10-31 14:53:24.441 TRACE tokio-runtime-worker loans::get_account_liquidity: [Parachain] account: , total_borrow_value: 0, total_collateral_value: 537464669262939120586
```

The different calculation leads to `total_collateral_value < redeem_dffects_value`.

### PR DESCRIPTION
**Pull request by yz89**
close #838

### CODE REVIEW

File: pallets/loans/src/lib.rs [hunk 1]
```diff
@@ -914,12 +914,13 @@ impl<T: Config> Pallet<T> {
...
             return Ok(FixedU128::zero());
         }
+        let exchange_rate = Self::exchange_rate(asset_id);
+        let underlying_amount =
+            Self::calc_underlying_amount(deposits.voucher_balance, exchange_rate)?;
         let market = Self::market(asset_id)?;
-        let collateral_amount = Self::exchange_rate(asset_id)
-            .checked_mul_int(market.collateral_factor.mul_floor(deposits.voucher_balance))
-            .ok_or(ArithmeticError::Overflow)?;
+        let effects_amount = market.collateral_factor.mul_ceil(underlying_amount);
```
Comment (GopherJ) [inline pallets/loans/src/lib.rs:921]: so the point is `mul_ceil` right?

Comment (GopherJ) [reply pallets/loans/src/lib.rs:921]: we should maybe check `mul_floor`, `mul_ceil` and understand each use case

**Review by GopherJ — APPROVED** [review]

File: pallets/loans/src/lib.rs (hunk 1 above)
Comment (yz89) [reply pallets/loans/src/lib.rs:921]: Yes, otherwise the test will go fail. 
https://github.com/parallel-finance/parallel/pull/839/files#diff-47f90f2e22bcae2eb1e7e0b3876dafa029fc292bf8f605a2b600aa56062bc517R73
